import { API_ROUTES, REACT_QUERY_KEYS } from '@/constants'
import useApiClient from '@/hooks/useApiClient'
import { toQueryString } from '@/lib/queryString/utils'
import { useQuery } from '@tanstack/react-query'

export interface IListPostParams {}
export type IListPostResp = {
  totalPages: number
  totalItems: number
  docs: Post[]
}

export interface Post {
  id: number
  title: string
  description: string
}

export default function useListPost(params: IListPostParams) {
  const apiClient = useApiClient()

  // return {
  //   isLoading: false,
  //   error: null,
  //   data: {
  //     totalPages: 2,
  //     totalItems: 12,
  //     docs: [
  //       {
  //         id: 1,
  //         title: 'computer vision',
  //         description: 'welcome mongDD',
  //       },
  //       {
  //         id: 2,
  //         title: 'computer vision',
  //         description: 'we------',
  //       },
  //       {
  //         id: 3,
  //         title: 'information technology',
  //         description: 'welcome mongDD',
  //       },
  //       {
  //         id: 4,
  //         title: 'information technology',
  //         description: 'welcome mongDD',
  //       },
  //       {
  //         id: 5,
  //         title: 'information technology',
  //         description: 'welcome mongDD',
  //       },
  //       {
  //         id: 6,
  //         title: 'information technology',
  //         description: 'welcome mongDD',
  //       },

  //       {
  //         id: 10,
  //         title: 'information technology8',
  //         description: 'welcome mongDD7=====',
  //       },
  //       {
  //         id: 11,
  //         title: 'information technology10',
  //         description: 'welcome mongDD7=====',
  //       },
  //       {
  //         id: 12,
  //         title: 'information technology10',
  //         description: 'welcome mongDD7=====',
  //       },
  //     ],
  //   },
  // }

  return useQuery({
    queryKey: [REACT_QUERY_KEYS.posts.list, params],
    queryFn: async () => {
      const { data } = (await apiClient.get(
        toQueryString({
          params,
          url: API_ROUTES.posts.list,
        })
      )) as {
        data: IListPostResp
      }
      return data
    },
    enabled: !!apiClient,
  })
}

// Generated by https://quicktype.io
